version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  backend:
    build: .
    command: ["flask", "run", "--host=0.0.0.0"]
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build: .
    # This command uses the stable 'threads' pool and the correct entry point
    command: ["celery", "-A", "services.celery_worker.celery", "worker", "--loglevel=info", "-P", "threads"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - backend